apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v2
spec:
  replicas: 3
  template:
    metadata:
      name: kubia-v2
      labels:
        app: kubia-v2
    spec:
      containers:
      - image: luksa/kubia:v2
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-v2
spec:
  type: LoadBalancer
  selector:
    app: kubia-v2
  ports:
  - port: 80
    targetPort: 8080
